src/Microsoft.Identity.Client.Extensions.Adal/AdalCache.cs
Turns out we actually need these things
=> Make AdalCache actually instantiable

src/Microsoft.Identity.Client.Extensions.Adal/AdalCache.cs, src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs, src/Shared/CrossPlatLock.cs
Found some minor issues stress testing cache locking
=> Changes from stress test

src/Microsoft.Identity.Client.Extensions.Adal/Microsoft.Identity.Client.Extensions.Adal.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj
Based on #44 
Csproj properties added are similar to those of MSAL.
=> Remove license file from nuget, add it as metadata

src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheStorage.cs, src/Microsoft.Identity.Client.Extensions.Msal/Properties/InternalsVisibleTo.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheStorageTests.cs
=> Fix null reference when reading fails

docs/keyring_fallback_proposal.md
This is currently blocking Az CLI and is an issue for PowerShell, both of which are CLIs that are expected to work on Linux over SSH. 
@rayluo @SomkaPe @schaabs - please review as the changes would need to be made in your extension libraries as well.
=> Proposal for Linux KeyRing fallback mechanism.

src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
=> Fix for #61 - ignore CacheChange event on Xamarin Mac

src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs, tests/ManualTestApp/ManualTestApp.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheHelperTests.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/TestCategories.cs
=> Fix for bug #81 - delete corrupted cache and bump to msal 4.14

sample/ManualTestApp/ManualTestApp.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj
Updating to MSAL 4.19.0
Tested
=> Updating to MSAL 4.19.0

src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheHelperTests.cs
Fix for https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/issues/90
Note that this does not address the issues found with VS + AzCLI
=> Deprecate Clear() and make it acquire a lock

src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
=> Fix for 115

Directory.Build.props, sample/ManualTestApp/ManualTestApp.csproj, sample/ManualTestApp/Program.cs, src/Microsoft.Identity.Client.Extensions.Adal/Microsoft.Identity.Client.Extensions.Adal.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj
Related: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2754
=> Update to MSAL 4.36 and add deterministic builds.

sample/ManualTestApp/ManualTestApp.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj
=> Upgrade to MSAL 4.36.1

sample/ManualTestApp/ManualTestApp.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheHelperTests.cs
=> Update to MSAL 4.38.0

release_build.yaml
Adding Software Bill Of Materials (SBOM) to release build
Manifest:
=> Adding Software Bill Of Materials (SBOM) to release build

Directory.Build.props, src/Microsoft.Identity.Client.Extensions.Msal/Accessors/DpApiEncryptedFileAccessor.cs, src/Microsoft.Identity.Client.Extensions.Msal/Accessors/FileAccessor.cs, src/Microsoft.Identity.Client.Extensions.Msal/Accessors/FileWithPermissions.cs, src/Microsoft.Identity.Client.Extensions.Msal/FileIOWithRetries.cs, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Storage.cs, src/Shared/SharedUtilities.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheStorageIntegrationTests.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheStorageTests.cs, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/TestHelper.cs
=> Set 600 permissions on fallback files

sample/ManualTestApp/ManualTestApp.csproj, src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj, tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/Microsoft.Identity.Client.Extensions.Msal.UnitTests.csproj
=> Update to MSAL 4.43.2

src/Shared/CrossPlatLock.cs, src/Shared/SharedUtilities.cs
GetProcess is called only once and formatting is done only once
=> Optimized for perf

src/Shared/Mac/LibSystem.cs
=> Fix for 180 - update path to libSystem

src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3627
=> Integrating with MSAL's IIdentityLogger

src/Shared/CrossPlatLock.cs
Fix for #204 
No existing unit tests in this area and writing one from scratch is not simple.
=> Fix for #204 - adjust sleep delay in file lock

src/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj
=> Update MSAL to 4.53.0
